/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bruna
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        caixagui_btn = new javax.swing.JButton();
        pedidogui_btn = new javax.swing.JButton();
        cardapiogui_btn = new javax.swing.JButton();
        fechar_btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        inicio_bar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        caixa_bar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pedido_bar = new javax.swing.JMenuItem();
        produto_bar = new javax.swing.JMenu();
        produto_bar2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ajuda_bar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        sair_bar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fundo.png"))); // NOI18N
        panelImage1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BEM VINDO AO MENU!");
        panelImage1.add(jLabel1);
        jLabel1.setBounds(70, 210, 270, 26);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        caixagui_btn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caixagui_btn.setText("CAIXA");
        caixagui_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixagui_btnActionPerformed(evt);
            }
        });
        jPanel2.add(caixagui_btn);
        caixagui_btn.setBounds(60, 120, 170, 27);

        pedidogui_btn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        pedidogui_btn.setText(" PEDIDO");
        pedidogui_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidogui_btnActionPerformed(evt);
            }
        });
        jPanel2.add(pedidogui_btn);
        pedidogui_btn.setBounds(60, 190, 170, 27);

        cardapiogui_btn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cardapiogui_btn.setText("PRODUTO");
        cardapiogui_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardapiogui_btnActionPerformed(evt);
            }
        });
        jPanel2.add(cardapiogui_btn);
        cardapiogui_btn.setBounds(60, 250, 170, 27);

        fechar_btn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fechar_btn.setText("X");
        fechar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_btnActionPerformed(evt);
            }
        });
        jPanel2.add(fechar_btn);
        fechar_btn.setBounds(-150, -40, 50, 40);

        panelImage1.add(jPanel2);
        jPanel2.setBounds(420, 0, 290, 380);

        jMenu4.setText("INICIO");

        inicio_bar.setText("INICIO");
        inicio_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_barActionPerformed(evt);
            }
        });
        jMenu4.add(inicio_bar);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("CAIXA");

        caixa_bar.setText("CAIXA");
        caixa_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_barActionPerformed(evt);
            }
        });
        jMenu1.add(caixa_bar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("PEDIDO");

        pedido_bar.setText("PEDIDO");
        pedido_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedido_barActionPerformed(evt);
            }
        });
        jMenu2.add(pedido_bar);

        jMenuBar1.add(jMenu2);

        produto_bar.setText("PRODUTO");

        produto_bar2.setText("PRODUTO");
        produto_bar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produto_bar2ActionPerformed(evt);
            }
        });
        produto_bar.add(produto_bar2);

        jMenuBar1.add(produto_bar);

        jMenu5.setText("AJUDA");

        ajuda_bar.setText("AJUDA");
        ajuda_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajuda_barActionPerformed(evt);
            }
        });
        jMenu5.add(ajuda_bar);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("SAIR");

        sair_bar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sair_bar.setText("SAIR");
        sair_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_barActionPerformed(evt);
            }
        });
        jMenu6.add(sair_bar);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(710, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caixagui_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixagui_btnActionPerformed
        new Caixa_GUI().setVisible(true);
    }//GEN-LAST:event_caixagui_btnActionPerformed

    private void pedidogui_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidogui_btnActionPerformed
        new Pedido_GUI().setVisible(true);
    }//GEN-LAST:event_pedidogui_btnActionPerformed

    private void cardapiogui_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapiogui_btnActionPerformed
        new Produto_GUI().setVisible(true);
    }//GEN-LAST:event_cardapiogui_btnActionPerformed

    private void fechar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fechar_btnActionPerformed

    private void inicio_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_barActionPerformed
        new Menu_GUI().setVisible(true);
    }//GEN-LAST:event_inicio_barActionPerformed

    private void pedido_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedido_barActionPerformed
        new Pedido_GUI().setVisible(true);
    }//GEN-LAST:event_pedido_barActionPerformed

    private void sair_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_barActionPerformed
      String x = JOptionPane.showInputDialog(null,"Deseja realmente sair? \n1-Sim\n2-Não" );
       int op = Integer.parseInt(x);
        if(op == 1){
            JOptionPane.showMessageDialog(null, "O programa foi fechado com sucesso!");
            System.exit(0);
        }else if(op == 2){
            JOptionPane.showMessageDialog(null, "O programa não foi fechado!");
        }else{
            JOptionPane.showMessageDialog(null, "ERRO!!!");
        }
    }//GEN-LAST:event_sair_barActionPerformed

    private void caixa_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_barActionPerformed
        new Caixa_GUI().setVisible(true);
    }//GEN-LAST:event_caixa_barActionPerformed

    private void produto_bar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produto_bar2ActionPerformed
        new Produto_GUI().setVisible(true);
    }//GEN-LAST:event_produto_bar2ActionPerformed

    private void ajuda_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajuda_barActionPerformed
        try{
            Desktop.getDesktop().open(new File("D:\\Mercado\\Ajuda Mercado.pdf"));
        }catch (IOException ex){
            Logger.getLogger(Menu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_ajuda_barActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajuda_bar;
    private javax.swing.JMenuItem caixa_bar;
    private javax.swing.JButton caixagui_btn;
    private javax.swing.JButton cardapiogui_btn;
    private javax.swing.JButton fechar_btn;
    private javax.swing.JMenuItem inicio_bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JMenuItem pedido_bar;
    private javax.swing.JButton pedidogui_btn;
    private javax.swing.JMenu produto_bar;
    private javax.swing.JMenuItem produto_bar2;
    private javax.swing.JMenuItem sair_bar;
    // End of variables declaration//GEN-END:variables
}
